import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { Navigation } from "../components";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Wedding Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
    </div>
  );
};

export default Home;
