import type { NextPage } from "next";
import { createClient } from "next-sanity";
import Head from "next/head";
import Image from "next/image";
import { Navigation, Headline, Introduction } from "../components";
import styles from "../styles/Home.module.css";

type PageProps = {
  infoText: {
    title: string;
    text: string;
  }[];
  headLine: {
    headline: string;
  }[];
  links: {
    title: string;
    link: string;
  }[];
};

const client = createClient({
  projectId: "mam500cy",
  apiVersion: "2022-09-12",
  useCdn: false,
  dataset: "production",
});

const Home: NextPage<PageProps> = ({ infoText, headLine, links }) => {
  console.log(infoText, headLine, links);
  return (
    <div>
      <Head>
        <title>Wedding Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation
        links={links
          .map((link) => ({ title: link.title, link: link.link }))
          .reverse()}
      />
      <Headline headLine={headLine[0].headline} />
      <Introduction title={infoText[0].title} introduction={infoText[0].text} />
    </div>
  );
};

export default Home;

export const getStaticProps = async () => {
  const headLine = await client.fetch(`*[_type == "headLine"]`);
  const infoText = await client.fetch(`*[_type == "infoText"]`);
  const links = await client.fetch(`*[_type == "link"]`);

  return {
    props: {
      headLine,
      infoText,
      links,
    },
  };
};
